#!/usr/bin/env bash

# called as `print_at <x-coord> <y-coord> <data>`
# print a string at a specific place on the screen
# x-coord and y-coord should be 0 <= coord <= screen_max
function print_at() {
    printf "\033[s"
    printf "\033[${2};${1}H %b" "${3}"
    printf "\033[u"
}


# in a non-interactive shell Bash doesn't fill in $LINES and $COLUMNS
# this uses a shell option and quick&dirty subshell trick to get Bash
# to actually give them to us
#
# called as `init_term <nameref for lines> <nameref for columns>`
function init_term() {
    local old_settings=$(shopt -p checkwinsize)
    shopt -s checkwinsize
    (:) # force Bash to update things
    local -n rvl="$1"
    local -n rvc="$2"
    rvl=$LINES
    rvc=$COLUMNS

    # NOTE: This looks ugly, but is completely safe. The text to
    # be evaluated is generated by Bash itself and cannot be
    # altered or manipulated without there being other, deeper
    # issues that mean this code could not be considered safe
    # for any reason. In general do not use eval, but here it is
    # entirely safe.
    eval "${old_settings}"
}

# Do pure integer math (truncating) to get a single-decimal digit
# precision percentage as a string
#
# calls as `make_percent <base> <of total> <result nameref>`
function make_percent() {
    local -i scaled_v=$(( $1 * 1000))
    local -i t=$2
    local -i p=$((scaled_v / t))
    local -n scaled_p="$3"
    local temp="${p}"
    local ip fp

    # pad the value out to 4 charcters
    # this gives 3 integer places and 1 decimal place
    while (( ${#temp} < 4 )); do
	temp="0$temp"
    done
    
    ip="${temp%?}" # extract the "integer" part of the zero-padded string
    fp="${temp: -1:1}" # extract the "decimal" part

    # hand Bash a zero-padded value as a string but tell it that it is an
    # integer and it'll interpret it as octal. We don't want that, so we
    # manually remove any leading zeros here
    while [[ ${ip:0:1} == "0" ]]; do
	ip=${ip:1}
    done

    # HACK1 If the integer part winds up zero-length, add back a single 0
    # because that means we only have a decimal part
    (( ${#ip} == 0 )) && ip="0"

    scaled_p="${ip}.${fp}"
}

# output a table near the bottom of the terminal with the current stats
function print_table() {
    local -n _raw_data="$1"  # first parameter is the associative array of the raw data we are outputting
    
    local -i lines=$2 # number of lines of the terminal
    local -i cols=$3  # number of columns of the terminal

    local -i enc=$(( ${#_raw_data[@]} / 4 )) # how many rows of data

    # NOTE: offset by at least twice the number of data rows plus one for the header
    local -i _numrows=$(( ($enc * 2) + 1 ))
    local -i toprow=$(( ($lines - $_numrows) - 1 )) # the top-most row is the header

    local -i idx
    local -a colnames=("USER" "SYSTEM" "IDLE") # for the header
    local -a colids=("user" "system" "idle") # these are the actual names used in the associative array

    # column positioning data -- user, system and idle percentages go into the table starting at these offsets
    local -Ai pos=([USER]=11 [SYSTEM]=21 [IDLE]=31)

    local crow=$(( $toprow + 1 )) # which row are we currently outputting at for the actual _table_ data?
    
    #print header
    local -i hdridx

    for (( hdridx = 0; hdridx < 3; hdridx++ )); do
	local cn=${colnames[$hdridx]}
	local -i cpos=${pos[$cn]}
	print_at ${cpos} ${toprow} "${cn}"
    done
    
    for (( idx = 0; idx < $(($_numrows - 5)); idx++ )); do
	local rn="cpu"
	(( idx > 0 )) && rn+="$(( idx - 1))"
	local -i j
	local -i zj=0
	[[ -v _raw_data["${rn},total"] ]] || continue
	local -i total_z=${_raw_data["${rn},total"]}
	print_at 0 ${crow} "${rn}"
	for (( j = 0; j < 3; j++ )); do
	    local kn="${rn},${colids[${j}]}"
	    local -i ci=${pos[${colnames[$j]}]}
	    local perc
	    make_percent ${_raw_data[$kn]} $total_z perc
	    print_at $ci $crow "          "
	    print_at $ci $crow "${perc}%"
	    zj=1
	done
	(( zj == 1 )) && crow=$(( $crow + 1 ))
    done
}

# break a `cpu stats` line from `/proc/stat` into its component elements
# store in the provided name-ref out parameter
#
# called as: `parse_line <output nameref> <input line>`
function parse_line() {
    local -n _pl_rval="$1"
    local -i _pl_user _pl_nice _pl_system _pl_idle _pl_iowait _pl_irq _pl_softirq _pl_steal _pl_guest _pl_guest_nice
    local _pl_id

    # until I started using Bash's `help` command, I didnt know that `read` could do this
    # Thanks Dave Eddy!
    read -r _pl_id _pl_user _pl_nice _pl_system _pl_idle _pl_iowait _pl_irq _pl_softirq _pl_steal _pl_guest _pl_guest_nice <<< "$2"

    _pl_rval['id']=$_pl_id
    _pl_rval['user']=$_pl_user
    _pl_rval['nice']=$_pl_nice
    _pl_rval['system']=$_pl_system
    _pl_rval['idle']=$_pl_idle
    _pl_rval['iowait']=$_pl_iowait
    _pl_rval['irq']=$_pl_irq
    _pl_rval['softirq']=$_pl_softirq
    _pl_rval['steal']=$_pl_steal
    _pl_rval['guest']=$_pl_guest
    _pl_rval['guest_nice']=$_pl_guest_nice
}

# simle helper, this creates a paired (almot csv) name to simulate a nested associative array
#
# called as: `make_data <nameref output> <raw data from 'parse_line'>`
# result if called with data incuding `id` of `cpu10`  would be similar to ([cpu10,user]=0 [cpu10,nice]=0 ...)
function make_data() {
    # make_data name values
    local -n _md_rval="$1"
    local -n _md_work="$2"
    local N
    for N in "user" "nice" "system" "idle" "iowait" "irq" "softirq" "steal" "guest" "guest_nice"; do
	local _md_k
	printf -v _md_k "%s,%s" "${_md_work['id']}" "${N}"
	_md_rval["${_md_k}"]="${_md_work[$N]}"
    done
}

function load_data() {
    # load_data output
    local -n _ld_rval="$1"
    local LINE
    
    local -a ALL_LINES

    # load the data
    mapfile ALL_LINES < "/proc/stat"
    
    _ld_rval=() # make sure output is clear
    
    #sort out only what we want
    for LINE in "${ALL_LINES[@]}"; do
	[[ $LINE =~ ^cpu[0-9]* ]] || continue

	local -A lv
	parse_line lv "$LINE"

	make_data _ld_rval lv
	unset lv
    done
}
